name = "dubai-fans-api"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[routes]]
pattern = "mtuaefans.com/api/*"
zone_name = "mtuaefans.com"

[[r2_buckets]]
binding = "R2"
bucket_name = "dubai-fans-storage"
preview_bucket_name = "dubai-fans-storage-dev"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "46c32db8cd2b4cd4a195498b858e6452"

[triggers]
crons = [
  "0 2 * * *",
  "0 3 * * SUN"
]

[vars]
NODE_ENV = "production"
PUBLIC_R2_PREFIXES = "public/assets"
AI_MODEL = "gpt-4o-mini"
